---
namespace: "tcharl"
name: "fail2ban"
version: "1.0.1"
description: "Role on top of the marvelous Robertdebock fail2ban role to with some more sshd hardening (suitable for krb5 setup)"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/fail2ban"
documentation: "https://github.com/OsgiliathEnterprise/fail2ban/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/fail2ban"
issues: "https://github.com/OsgiliathEnterprise/fail2ban/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "fail2ban"
  - "sshd"
  - "linux"
