---

- name: Requirements | import epel role
  ansible.builtin.import_role:
    name: robertdebock.epel
  become: True

- name: Requirements | import bootstrap role
  ansible.builtin.include_role:
    name: robertdebock.bootstrap
  vars:
    bootstrap_become: true

- name: Requirements | import fail2ban role
  ansible.builtin.import_role:
    name: robertdebock.fail2ban
  become: True
