---

- name: Requirements | import epel role
  ansible.builtin.import_role:
    name: robertdebock.epel
  become: True

- name: Requirements | import bootstrap role
  ansible.builtin.import_role:
    name: robertdebock.bootstrap
  become: True

- name: Requirements | import fail2ban role # use include to avoid handler issue
  ansible.builtin.include_role:
    name: robertdebock.fail2ban
  vars:
    ansible_become: True
