---

- name: Requirements | import epel role
  ansible.builtin.import_role:
    name: robertdebock.epel
  become: True

- name: Requirements | import bootstrap role
  ansible.builtin.import_role:
    name: robertdebock.bootstrap
  become: True

- name: Requirements | import fail2ban role
  ansible.builtin.import_role:
    name: robertdebock.fail2ban
  become: True
  failed_when: False
